"""Add diagnosis and comment columns to DiagnosticReport

Revision ID: 973744c0d849
Revises: 
Create Date: 2024-12-09 01:41:20.701078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973744c0d849'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnosis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic_report', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('diagnosis')

    # ### end Alembic commands ###
